#!/usr/bin/env python

import os
import sys
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_NAME, MODEL_CACHE, TOKEN_CACHE

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    cache_dir=TOKEN_CACHE
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    cache_dir=MODEL_CACHE
)